apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-scg-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-scg-web-app
    tanzu.app.live.view: true
    tanzu.app.live.view.application.name: tanzu-scg-web-app
  annotations:
    autoscaling.knative.dev/minScale: "5"
spec:
  source:
    git:
      url: https://github.com/ksankaranara-vmw/gs-gateway
      ref:
        branch: main
